name: list_french_words
description: This package contains a list of french words for use in other tools. From spell checkers, to ngram analysis.
repository: https://github.com/ALMDart/dart_list_french_words
homepage: https://github.com/ALMDart/dart_list_french_words
version: 0.1.0+2

environment:
  sdk: '>=2.7.0 <3.0.0'

dev_dependencies:
  effective_dart: ^1.2.1
  test: ^1.6.0
